#-------------------------------
# General Site Settings
title: Chamsule
logo: logo.svg
description: Zolan is modern minimal theme for Jekyll


#-------------------------------
# Author Settings
author:
  name: Chamsuletech
  say-hello: 안녕하세요!, 
  bio: 참슬테크의 기술 블로그 입니다.
